### ISSUE TITLE
Multiline comments fails eslint

### ISSUE THREAD

**Issue by moficodes** [bee-travels/openapi-comment-parser#2]
If there is a multiline comment that is not for openapi it fails eslint

**Comment by bourdakos1** [comment]
@moficodes Thank you so much for submitting this issue and bringing attention to the possible bug. Do you mind providing error messages/steps to reproduce the bug? Possibly an example repo with the issue?

**Comment by bourdakos1** [comment]
@moficodes looks like the issue was with `eslint-plugin-openapi`, it should be fixed in `v0.0.4`

Thank you for your contribution 🎉
