### ISSUE TITLE
Dynamic spec definitions

### ISSUE THREAD

**Issue by nenadpnc** [bee-travels/openapi-comment-parser#20]
Hi, I have a use case where i would like to set `title` and/or `version` of spec definition dynamically, based on current environment or api version. Currently, it seems that this is not so straightforward with yaml. 

```typescript
const definition = {
  openapi: '',
  info: {
    title: '',
    version: '', // < -- these should be set dynamically, not parsed from static yaml file, if possible
  },
};
```

Would love the option to pass spec definitions to the parser, either as a part of the `ParserOptions` in `openapi(options: ParserOptions)` or as a second argument.
Or, maybe there is already solution for this and i'm missing something :/ .

If not, i'm also open to creating PR for this feature.

Btw, big fan of this project, thanks for creating it 👍 .

**Comment by bourdakos1** [comment]
Hi thanks 😊 

I think if you need to set something dynamically you could try something like this:
```js
let definition = openapi(options: ParserOptions)
definition.info.title = "my title"
```

But I’m also open to adding a feature for a definition override as a parser option. A PR would be great :)

**Comment by nenadpnc** [comment]
Aah, that makes a lot of sense, totally missed that `openapi()` call returns the whole definition object 🙄.
Thank you for quick response, closing this issue 👍 .
