### ISSUE TITLE
File Type Support

### ISSUE THREAD

**Issue by sjw0010** [bee-travels/openapi-comment-parser#30]
Not really an issue but more of a request. Are ['.js', '.cjs', '.mjs', '.ts', '.tsx', '.jsx', '.yaml', '.yml'] the only file types supported? This is a really useful tool for my process. I would love support for '.java' files? CLI usage only obviously. 

Cheers!

**Comment by bourdakos1** [comment]
You can add a config file to your project that specifies other extensions

**Comment by sjw0010** [comment]
Sweet. Thanks!

**Comment by sjw0010** [comment]
Sorry, would you have an example of what that config format would need to look like?

**Comment by bourdakos1** [comment]
You should be able to run: `openapi-comment-parser --init` to generate one
